import browserHistory from 'react-router/lib/browserHistory';

import MODAL_MESSAGES from 'constants/messages';
import {
  CLOSE_MODAL,
  SESSION_EXPIRED,
  LOG_OUT,
  REGISTRATION_REQUEST,
  LOGIN_REQUEST,
  EDIT_EXPENSE,
} from 'constants/actionTypes';
import sendRequest from './requestActions';

/**
 * Create an action with no payload
 *
 * @returns {{type: string}}
 */
function action(type) {
  return { type };
}

/**
 * Change event on a form input
 *
 * @param {string} type
 * @param {string} form - form the input belongs to
 * @param {string} field - field the input is related to
 * @param {string} value - value on the input
 * @returns {{type: string, id: string, value: string}}
 */
function inputChange(type, form, field, value) {
  return {
    type,
    form,
    field,
    value,
  };
}

/**
 * Dispatch the request associated to the form of a given action type
 *
 * @param {Event} e
 * @param {string} type
 * @return {function}
 */
function submitForm(e, type) {
  // prevent default so the form submission doesn't force a page reload
  e.preventDefault();

  return sendRequest(
    type,
    { triggerId: e.currentTarget.id }
  );
}

/**
 * Redirect to a given URI
 *
 * @param {string} uri
 */
function redirect(uri) {
  browserHistory.push(uri);
}

/**
 * Log user out and redirect to login page afterwards
 *
 * @return {function}
 */
function logOut() {
  return (dispatch) => {
    dispatch(action(LOG_OUT));

    redirect('/');
  };
}

/**
 * Handle the click of the button on the modal dialog, checking if the state requires a navigation
 * to another page before closing the dialog
 *
 * @returns {function}
 */
function modalBtnClick() {
  return (dispatch, getState) => {
    const modalMsg = getState().modals.msgModal.msg;

    if ([
      MODAL_MESSAGES[REGISTRATION_REQUEST],
      MODAL_MESSAGES[LOGIN_REQUEST],
    ].includes(modalMsg)
    ) {
      redirect('/');
    } else if (modalMsg === MODAL_MESSAGES[SESSION_EXPIRED]) {
      // log user out when server returns session expired
      return dispatch(logOut());
    }

    return dispatch(action(CLOSE_MODAL));
  };
}

/**
 * Date object generated by the moment module
 *
 * @typedef {object} MomentDate
 */

/**
 * The date selected on the date or time pickers used to create/edit expenses has been changed
 *
 * @param {string} type
 * @param {('create'|'edit'|'$gte_date'|'$lte_date')} form - The form or filter input where the
 * change happened
 * @param {MomentDate} date
 * @returns {{type: string, form: ('create'|'edit'|'$gte_date'|'$lte_date'), date: MomentDate}}
 */
function expenseDatetimeChange(type, form, date) {
  return { type, form, date };
}

/**
 * Turn the given expense row editable
 *
 * @param {ObjectId} expenseId
 * @return {{type: string, expenseId: ObjectId}}
 */
function editExpense(expenseId) {
  return { type: EDIT_EXPENSE, expenseId };
}

export {
  sendRequest,
  action,
  inputChange,
  submitForm,
  logOut,
  modalBtnClick,
  expenseDatetimeChange,
  editExpense,
};
