const REQUEST = '_REQUEST';
const ERROR = '_ERROR';
const SUCCESS = '_SUCCESS';

const INPUT_CHANGE = 'input_change';
const LOGIN_REGISTRATION_INPUT_CHANGE = `login_registration_${INPUT_CHANGE}`;
const EXPENSES_INPUT_CHANGE = `expenses_${INPUT_CHANGE}`;
const EXPENSE_DATE_CHANGE = 'date_change';
const FILTER_DATE_CHANGE = 'filter_date_change';
const FILTER_INPUT_CHANGE = 'filter_input_change';
const CLEAR_EXPENSES_FILTER = 'clear_expenses__filter';
const TOGGLE_DAY_WEEK_EXPENSES = 'toggle_day_week_expenses';
const CLOSE_MODAL = 'close_modal';
const SESSION_EXPIRED = 'session_expired';
const LOG_OUT = 'log_out';

const REGISTRATION_REQUEST = `registration${REQUEST}`;

const LOGIN_REQUEST = `login${REQUEST}`;

const CREATE_EXPENSE_REQUEST = `create_expense${REQUEST}`;

const GET_EXPENSES_REQUEST = `GET_EXPENSES${REQUEST}`;
const GET_EXPENSES_REQUEST_ON_LOAD = `${GET_EXPENSES_REQUEST}_on_load`;

const DELETE_EXPENSE_REQUEST = `delete_expense${REQUEST}`;

const EDIT_EXPENSE = 'edit_expense';
const CANCEL_EDIT_EXPENSE = `cancel_${EDIT_EXPENSE}`;
const EDIT_EXPENSE_REQUEST = EDIT_EXPENSE + REQUEST;

const OPEN_INPUT_MODAL = 'OPEN_INPUT_MODAL';
const MODAL_INPUT_CHANGE = 'MODAL_INPUT_CHANGE';

const CREATE_CATEGORY_REQUEST = `CREATE_CATEGORY${REQUEST}`;

export {
  REQUEST,
  ERROR,
  SUCCESS,
  LOGIN_REGISTRATION_INPUT_CHANGE,
  EXPENSES_INPUT_CHANGE,
  EXPENSE_DATE_CHANGE,
  FILTER_DATE_CHANGE,
  FILTER_INPUT_CHANGE,
  CLEAR_EXPENSES_FILTER,
  TOGGLE_DAY_WEEK_EXPENSES,
  CLOSE_MODAL,
  SESSION_EXPIRED,
  LOG_OUT,
  REGISTRATION_REQUEST,
  LOGIN_REQUEST,
  CREATE_EXPENSE_REQUEST,
  GET_EXPENSES_REQUEST,
  GET_EXPENSES_REQUEST_ON_LOAD,
  DELETE_EXPENSE_REQUEST,
  EDIT_EXPENSE,
  CANCEL_EDIT_EXPENSE,
  EDIT_EXPENSE_REQUEST,
  OPEN_INPUT_MODAL,
  MODAL_INPUT_CHANGE,
  CREATE_CATEGORY_REQUEST,
};
