import 'whatwg-fetch';
import hashHistory from 'react-router/lib/hashHistory';

import sendRequest from './requestActions';
import { MODAL_MESSAGES } from 'constants/messages';
import {
  CLEAR_EXPENSES_FILTER,
  CLOSE_MODAL,
  REGISTRATION_REQUEST,
  LOGIN_REQUEST,
  EDIT_EXPENSE,
  CANCEL_EDIT_EXPENSE,
} from 'constants/actionTypes';

/**
 * Change event on a form input
 *
 * @param {string} type
 * @param {string} form - form the input belongs to
 * @param {string} field - field the input is related to
 * @param {string} value - value on the input
 * @returns {{type: string, id: string, value: string}}
 */
function inputChange(type, form, field, value) {
  return {
    type,
    form,
    field,
    value,
  };
}

/**
 * Handle the click of the button on the modal dialog, checking if the state requires a navigation
 * to another page before closing the dialog
 *
 * @returns {function}
 */
function modalBtnClick() {
  return (dispatch, getState) => {
    const modalMsg = getState().authenticated.modal.msg;

    if ([
        MODAL_MESSAGES[REGISTRATION_REQUEST],
        MODAL_MESSAGES[LOGIN_REQUEST],
      ].includes(modalMsg)
    ) {
      hashHistory.push('/');
    }

    return dispatch(closeModal());
  };
}

/**
 * Close modal dialog
 *
 * @returns {{type: string}}
 */
function closeModal() {
  return { type: CLOSE_MODAL };
}

/**
 * Date object generated by the moment module
 *
 * @typedef {object} MomentDate
 */

/**
 * The date selected on the date or time pickers used to create/edit expenses has been changed
 *
 * @param {string} type
 * @param {('create'|'edit'|'$gte_date'|'$lte_date')} form - The form or filter input where the
 * change happened
 * @param {MomentDate} date
 * @returns {{type: string, form: ('create'|'edit'|'$gte_date'|'$lte_date'), date: MomentDate}}
 */
function expenseDatetimeChange(type, form, date) {
  return { type, form, date };
}

/**
 * Turn the given expense row editable
 *
 * @param {ObjectId} expenseId
 * @return {{type: string, expenseId: ObjectId}}
 */
function editExpense(expenseId) {
  return { type: EDIT_EXPENSE, expenseId };
}

function cancelEditExpense() {
  return { type: CANCEL_EDIT_EXPENSE };
}

function clearExpensesFilter() {
  return { type: CLEAR_EXPENSES_FILTER };
}

export {
  inputChange,
  sendRequest,
  modalBtnClick,
  closeModal,
  expenseDatetimeChange,
  editExpense,
  cancelEditExpense,
  clearExpensesFilter
};
