import 'whatwg-fetch';
import hashHistory from 'react-router/lib/hashHistory';

import {
  INPUT_CHANGE,
  CLOSE_MODAL
} from 'constants/actionTypes';
import {
  MODAL_REGISTRATION_SUCC,
  MODAL_LOGIN_SUCC
} from 'constants/messages';
import sendRequest from './requestActions';

/**
 * Change event on a form input
 *
 * @param {string} id - ID belonging to a form input
 * @param {string} value - value on the input
 * @returns {{type: string, id: string, value: string}}
 */
function inputChange(id, value) {
  return {
    type: INPUT_CHANGE,
    id,
    value,
  };
}

/**
 * A request of the given type has been sent to the API
 *
 * @param {string} type
 * @returns {{type: string}}
 */
function initRequest(type) {
  return { type };
}

/**
 * Handle the click of the button on the modal dialog, checking if the state requires a navigation
 * to another page before closing the dialog
 *
 * @returns {function}
 */
function modalBtnClick() {
  return (dispatch, getState) => {
    const modalMsg = getState().authenticated.modal.msg;

    if ([MODAL_REGISTRATION_SUCC, MODAL_LOGIN_SUCC].includes(modalMsg)) {
      hashHistory.push('/');
    }

    return dispatch(closeModal());
  };
}

/**
 * Close modal dialog
 *
 * @returns {{type: string}}
 */
function closeModal() {
  return { type: CLOSE_MODAL };
}

/**
 * Date object generated by the moment module
 *
 * @typedef {object} MomentDate
 */

/**
 * The date selected on the date or time pickers used to create expenses has been changed
 *
 * @param {string} type
 * @param {MomentDate} date
 * @returns {{type: string, date: MomentDate}}
 */
function createExpenseDatetimeChange(type, date) {
  return { type, date };
}

export {
  inputChange,
  initRequest,
  sendRequest,
  modalBtnClick,
  closeModal,
  createExpenseDatetimeChange
};
