import 'whatwg-fetch';
import hashHistory from 'react-router/lib/hashHistory';

import sendRequest from './requestActions';
import { MODAL_MESSAGES } from 'constants/messages';
import {
  INPUT_CHANGE,
  CLOSE_MODAL,
  REGISTRATION_REQUEST,
  LOGIN_REQUEST
} from 'constants/actionTypes';

/**
 * Change event on a form input
 *
 * @param {string} id - ID belonging to a form input
 * @param {string} value - value on the input
 * @returns {{type: string, id: string, value: string}}
 */
function inputChange(id, value) {
  return {
    type: INPUT_CHANGE,
    id,
    value,
  };
}

/**
 * Handle the click of the button on the modal dialog, checking if the state requires a navigation
 * to another page before closing the dialog
 *
 * @returns {function}
 */
function modalBtnClick() {
  return (dispatch, getState) => {
    const modalMsg = getState().authenticated.modal.msg;

    if ([
        MODAL_MESSAGES[REGISTRATION_REQUEST],
        MODAL_MESSAGES[LOGIN_REQUEST],
      ].includes(modalMsg)
    ) {
      hashHistory.push('/');
    }

    return dispatch(closeModal());
  };
}

/**
 * Close modal dialog
 *
 * @returns {{type: string}}
 */
function closeModal() {
  return { type: CLOSE_MODAL };
}

/**
 * Date object generated by the moment module
 *
 * @typedef {object} MomentDate
 */

/**
 * The date selected on the date or time pickers used to create expenses has been changed
 *
 * @param {string} type
 * @param {MomentDate} date
 * @returns {{type: string, date: MomentDate}}
 */
function createExpenseDatetimeChange(type, date) {
  return { type, date };
}

export {
  inputChange,
  sendRequest,
  modalBtnClick,
  closeModal,
  createExpenseDatetimeChange
};
